# azure-pipelines.yml
trigger:
- main

pool: Default

variables:
  imageRepository: 'serviceexampleacr.azurecr.io/serviceexample'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: Build
    displayName: Build Container Image
    steps:
    - script: |
        echo "Installing Podman..."
        sudo apt update
        sudo apt install -y podman
      displayName: 'Install Podman'
      
    - script: |
        echo "Logging into ACR..."
        podman login $(imageRepository) --username "$(acrUsername)" --password "$(acrPassword)"
        
        echo "Building image..."
        podman build -t $(imageRepository):$(tag) -f Dockerfile .
        
        echo "Pushing image..."
        podman push $(imageRepository):$(tag)
        
        # Also tag as latest
        podman tag $(imageRepository):$(tag) $(imageRepository):latest
        podman push $(imageRepository):latest
        
        echo "Build completed successfully!"
      displayName: 'Build and Push Image'
