# azure-pipelines.yml
trigger:
- main

pool: SelfHostedPool

steps:
- checkout: self

- script: |
    dotnet restore
    dotnet build --configuration Release --no-restore
    dotnet test --configuration Release --verbosity minimal
  displayName: 'Build and Test'

- script: |
    echo "Building container image..."
    podman build -t serviceexample:$(Build.BuildId) -f Dockerfile .
    echo "✅ Build completed on self-hosted agent"
  displayName: 'Build Container'

- script: |
    echo "🎉 DEMO SUCCESS!"
    echo "Running on: $(Agent.MachineName)"
    echo "Pool: $(Agent.PoolName)"
  displayName: 'Success Message'
