# azure-pipelines.yml
trigger:
- main

pool: SelfHostedPool

variables:
  imageRepository: 'serviceexampleacr.azurecr.io/serviceexample'
  tag: '$(Build.BuildId)'

steps:
- script: |
    echo "=== Starting Build Process ==="
    echo "Build ID: $(Build.BuildId)"
    echo "Pool: SelfHostedPool"
    echo "Image: $(imageRepository):$(tag)"
    
    # Install Podman
    echo "Installing Podman..."
    sudo apt update
    sudo apt install -y podman
    
    # Login to ACR
    echo "Logging into Azure Container Registry..."
    podman login $(imageRepository) --username "$(acrUsername)" --password "$(acrPassword)"
    
    # Build image
    echo "Building Docker image..."
    podman build -t $(imageRepository):$(tag) -f Dockerfile .
    
    # Push image with build ID
    echo "Pushing image to ACR..."
    podman push $(imageRepository):$(tag)
    
    # Also tag and push as latest
    echo "Tagging and pushing as latest..."
    podman tag $(imageRepository):$(tag) $(imageRepository):latest
    podman push $(imageRepository):latest
    
    echo "=== Build Completed Successfully! ==="
    echo "Image pushed: $(imageRepository):$(tag)"
    echo "Image pushed: $(imageRepository):latest"
  displayName: 'Build and Push Container Image'
