trigger:
  branches:
    include:
      - main

variables:
  IMAGE_NAME: 'serviceexample'
  TAG: '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    displayName: "Build, Test, and Push Docker Image"
    jobs:
      - job: Build
        pool:
          name: SelfHostedPool   # your self-hosted agent pool
        steps:
          # 1️⃣ Install .NET SDK
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '9.0.x'

          # 2️⃣ Restore dependencies
          - script: |
              dotnet restore
            displayName: 'Restore .NET Dependencies'

          # 3️⃣ Build the solution
          - script: |
              dotnet build ServiceExample.sln --configuration Release
            displayName: 'Build Solution'

          # 4️⃣ Run Unit Tests
          - script: |
              dotnet test UnitTests/UnitTests.csproj --configuration Release --verbosity normal
            displayName: 'Run Unit Tests'

          # 5️⃣ Build and Push Docker image to ACR
          - task: Docker@2
            inputs:
              containerRegistry: 'serviceexampleacr'   # your Azure DevOps ACR service connection name
              repository: '$(IMAGE_NAME)'              # repository name in ACR
              command: 'buildAndPush'
              dockerfile: 'Dockerfile'
              tags: |
                $(TAG)
                latest
