trigger:
  branches:
    include:
      - main

variables:
  IMAGE_NAME: 'serviceexample'
  TAG: '$(Build.BuildId)'
  LATEST_TAG: 'latest'
  BUILD_CONTEXT: 'ServiceExample'

stages:
  - stage: BuildAndPush
    displayName: "Build, Test, and Push Docker Image"
    jobs:
      - job: Build
        pool:
          name: SelfHostedPool
        steps:
          - checkout: self
            displayName: 'Checkout source code'

          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '9.0.x'
            displayName: 'Install .NET SDK 9.0.x'

          - task: Cache@2
            inputs:
              key: 'nuget | "$(Agent.OS)" | **/*.csproj'
              path: ~/.nuget/packages
            displayName: 'Cache NuGet packages'

          - script: dotnet restore --verbosity quiet
            displayName: 'Restore .NET Dependencies'

          - script: dotnet build ServiceExample/ServiceExample.csproj -c Release --no-restore
            displayName: 'Build Project'

          - script: dotnet test UnitTests/UnitTests.csproj --configuration Release --no-build --verbosity minimal
            displayName: 'Run Unit Tests'

          # 🔥 SIMPLE DOCKER LOGIN (This will work)
          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              containerRegistry: 'serviceexampleacr'
              command: 'login'

          # 🔥 BUILD AND PUSH
          - task: Docker@2
            displayName: 'Build and Push Docker Image'
            inputs:
              command: 'buildAndPush'
              containerRegistry: 'serviceexampleacr'
              repository: '$(IMAGE_NAME)'
              dockerfile: 'Dockerfile'
              buildContext: '$(BUILD_CONTEXT)'
              tags: |
                $(TAG)
                $(LATEST_TAG)
