trigger:
  branches:
    include:
      - main

variables:
  IMAGE_NAME: 'serviceexample'
  TAG: '$(Build.BuildId)'
  # Pipeline variables
  buildConfiguration: '$(BuildConfiguration)'
  aspnetcoreEnvironment: '$(ASPNETCORE_ENVIRONMENT)'

stages:
  - stage: BuildAndPush
    displayName: "Build and Push Docker Image"
    jobs:
      - job: Build
        pool:
          name: SelfHostedPool
        steps:
          - checkout: self
            displayName: 'Checkout source code'

          - script: dotnet restore
            displayName: 'Restore .NET Dependencies'
            env:
              DOTNET_CLI_TELEMETRY_OPTOUT: $(DOTNET_CLI_TELEMETRY_OPTOUT)

          - script: dotnet build --configuration $(buildConfiguration) --no-restore
            displayName: 'Build Project'

          - script: dotnet test --configuration $(buildConfiguration) --verbosity minimal
            displayName: 'Run Unit Tests'

          # BUILD DOCKER IMAGE with environment variables
          - task: Bash@3
            displayName: 'Build Docker Image'
            inputs:
              targetType: 'inline'
              script: |
                echo "=== Building Docker Image ==="
                docker build -t serviceexampleacr.azurecr.io/$(IMAGE_NAME):$(TAG) .
                echo "✅ Build completed"

          # PUSH using secret variables
          - task: Bash@3
            displayName: 'Push Docker Image'
            inputs:
              targetType: 'inline'
              script: |
                echo "=== Pushing Docker Image ==="
                
                # Use secret variables for authentication
                echo "$(ACR_PASSWORD)" | docker login serviceexampleacr.azurecr.io --username "$(ACR_USERNAME)" --password-stdin
                docker push serviceexampleacr.azurecr.io/$(IMAGE_NAME):$(TAG)
                
                echo "✅ Push completed successfully"
