trigger:
  branches:
    include:
      - main

variables:
  IMAGE_NAME: 'serviceexample'
  TAG: '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    displayName: "Build and Push Docker Image"
    jobs:
      - job: Build
        pool:
          name: SelfHostedPool
        steps:
          - checkout: self
            displayName: 'Checkout source code'

          - script: dotnet restore
            displayName: 'Restore .NET Dependencies'

          - script: dotnet build --configuration Release --no-restore
            displayName: 'Build Project'

          - script: dotnet test --configuration Release --verbosity minimal
            displayName: 'Run Unit Tests'

          # 🔥 TEMPORARY: Debug Docker build
          - script: |
              echo "=== Docker System Info ==="
              docker system df
              echo "=== Building Docker Image ==="
              time docker build -t serviceexampleacr.azurecr.io/$(IMAGE_NAME):$(TAG) .
              echo "=== Build Complete ==="
            displayName: 'Debug Docker Build'
            
          # 🔥 TEMPORARY: Debug Docker push
          - script: |
              echo "=== Pushing Docker Image ==="
              az acr login --name serviceexampleacr
              time docker push serviceexampleacr.azurecr.io/$(IMAGE_NAME):$(TAG)
              echo "=== Push Complete ==="
            displayName: 'Debug Docker Push'
