trigger:
  branches:
    include:
      - main

variables:
  IMAGE_NAME: 'serviceexample'
  TAG: '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    displayName: "Build and Push Docker Image"
    jobs:
      - job: Build
        pool:
          name: SelfHostedPool
        steps:
          # 1️⃣ Install .NET SDK
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '9.0.x'

          # 2️⃣ Restore and Build the .NET Project
          - script: |
              dotnet restore
              dotnet build --configuration Release
            displayName: 'Restore and Build Project'

          # 3️⃣ Run Unit Tests
          - script: |
              dotnet test --no-build --verbosity normal
            displayName: 'Run Unit Tests'

          # 4️⃣ Build and Push Docker image to ACR
          - task: Docker@2
            inputs:
              containerRegistry: 'serviceexampleacr'   # your service connection name
              repository: '$(IMAGE_NAME)'              # repository name in ACR
              command: 'buildAndPush'
              dockerfile: 'Dockerfile'
              tags: |
                $(TAG)
