# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'serviceexampleacr.azurecr.io/serviceexample'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: Build
    displayName: Build Docker Image
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: 'serviceexampleacr'
        tags: |
          $(tag)
          latest

- stage: Test
  displayName: Run Tests
  dependsOn: Build
  jobs:
  - job: Test
    displayName: Run Unit Tests
    steps:
    - script: |
        echo "Running tests would go here"
        # Add your test commands here
      displayName: 'Run Tests'

- stage: Deploy
  displayName: Deploy to Kubernetes
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: Deploy Application
    steps:
    - task: KubernetesManifest@0
      displayName: Deploy to Kubernetes
      inputs:
        action: 'deploy'
        namespace: 'default'
        manifests: |
          $(Pipeline.Workspace)/manifests/*
        imagePullSecrets: |
          acr-secret
