# azure-pipelines.yml
trigger:
- main

pool: Default

variables:
  imageRepository: 'serviceexampleacr.azurecr.io/serviceexample'
  tag: '$(Build.BuildId)'

steps:
- task: CmdLine@2
  displayName: 'Install Podman'
  inputs:
    script: |
      sudo apt update
      sudo apt install -y podman

- task: CmdLine@2
  displayName: 'Login to ACR'
  inputs:
    script: |
      podman login $(imageRepository) --username "$(acrUsername)" --password "$(acrPassword)"

- task: CmdLine@2
  displayName: 'Build and Push Image'
  inputs:
    script: |
      podman build -t $(imageRepository):$(tag) -f Dockerfile .
      podman push $(imageRepository):$(tag)
      podman tag $(imageRepository):$(tag) $(imageRepository):latest
      podman push $(imageRepository):latest
      echo "✅ Build and push completed successfully!"
