# azure-pipelines.yml
trigger:
- main

pool: SelfHostedPool

variables:
  imageRepository: 'serviceexampleacr.azurecr.io/serviceexample'
  tag: '$(Build.BuildId)'

steps:
- script: |
    podman login $(imageRepository) --username "$(acrUsername)" --password "$(acrPassword)"
    podman build -t $(imageRepository):$(tag) -f Dockerfile .
    podman push $(imageRepository):$(tag)
    podman tag $(imageRepository):$(tag) $(imageRepository):latest
    podman push $(imageRepository):latest
    echo "✅ Image pushed to ACR: $(imageRepository):$(tag)"
  displayName: 'Build and Push'
  env:
    acrUsername: $(acrUsername)
    acrPassword: $(acrPassword)
