trigger:
  branches:
    include:
      - main

variables:
  IMAGE_NAME: 'serviceexample'
  TAG: '$(Build.BuildId)'
  LATEST_TAG: 'latest'

stages:
  - stage: BuildAndPush
    displayName: "Build, Test, and Push Docker Image"
    jobs:
      - job: Build
        pool:
          name: SelfHostedPool
        steps:
          # 1️⃣ Checkout source code
          - checkout: self
            displayName: 'Checkout source code'

          # 2️⃣ Install .NET SDK
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '9.0.x'
            displayName: 'Install .NET SDK 9.0.x'

          # 3️⃣ Cache NuGet packages
          - task: Cache@2
            inputs:
              key: 'nuget | "$(Agent.OS)" | **/*.csproj'
              path: ~/.nuget/packages
            displayName: 'Cache NuGet packages'

          # 4️⃣ Restore dependencies
          - script: dotnet restore
            displayName: 'Restore .NET Dependencies'

          # 5️⃣ Build project
          - script: dotnet build ServiceExample/ServiceExample.csproj -c Release
            displayName: 'Build Project'

          # 6️⃣ Run Unit Tests
          - script: dotnet test UnitTests/UnitTests.csproj --configuration Release --verbosity normal
            displayName: 'Run Unit Tests'

          # 7️⃣ Docker login
          - task: Docker@2
            displayName: 'Docker Login to ACR'
            inputs:
              containerRegistry: 'serviceexampleacr'
              command: login
              enableVerboseLogging: true

          # 8️⃣ Docker build with incremental cache
          - task: Docker@2
            displayName: 'Docker Build'
            inputs:
              containerRegistry: 'serviceexampleacr'
              repository: '$(IMAGE_NAME)'
              command: build
              dockerfile: 'Dockerfile'
              tags: |
                $(TAG)
                $(LATEST_TAG)
              buildContext: '.'
              enableVerboseLogging: true
              arguments: '--cache-from $(IMAGE_NAME):latest'

          # 9️⃣ Docker push
          - task: Docker@2
            displayName: 'Docker Push'
            inputs:
              containerRegistry: 'serviceexampleacr'
              repository: '$(IMAGE_NAME)'
              command: push
              tags: |
                $(TAG)
                $(LATEST_TAG)
              enableVerboseLogging: true
