trigger:
  branches:
    include:
      - main

variables:
  IMAGE_NAME: 'serviceexample'
  TAG: '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    displayName: "Build and Push Docker Image"
    jobs:
      - job: Build
        pool:
          name: SelfHostedPool
        timeoutInMinutes: 8
        steps:
          - checkout: self
            displayName: 'Checkout source code'

          - script: dotnet restore
            displayName: 'Restore .NET Dependencies'

          - script: dotnet build --configuration Release --no-restore
            displayName: 'Build Project'

          - script: dotnet test --configuration Release --verbosity minimal
            displayName: 'Run Unit Tests'

          # 🔥 DEBUG: Manual Docker commands with better logging
          - task: Bash@3
            displayName: 'Debug Docker Build'
            inputs:
              targetType: 'inline'
              script: |
                echo "=== Starting Docker Build ==="
                date
                docker build -t serviceexampleacr.azurecr.io/$(IMAGE_NAME):$(TAG) . --progress=plain
                echo "=== Build Completed ==="
                date

          - task: Bash@3
            displayName: 'Debug Docker Push'
            inputs:
              targetType: 'inline'
              script: |
                echo "=== Starting Docker Push ==="
                date
                # Login and push in one command
                az acr login --name serviceexampleacr
                docker push serviceexampleacr.azurecr.io/$(IMAGE_NAME):$(TAG)
                echo "=== Push Completed ==="
                date
