# gitops/applications/serviceexample-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serviceexample
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/priyankakanna/ServiceExample
    targetRevision: main
    path: helm-charts/serviceexample
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: "latest"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
