# helm-charts/serviceexample/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "serviceexample.fullname" . }}
  labels:
    {{- include "serviceexample.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "serviceexample.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "serviceexample.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.app.env.ASPNETCORE_ENVIRONMENT | quote }}
            # TLS-Enabled Connection Strings
            - name: Aspire__MongoDB__Driver__ConnectionString
              value: {{ if .Values.mongodb.tls.enabled }}"mongodb://{{ include "serviceexample.fullname" . }}-mongodb:27017/?ssl=true&tlsCAFile=/etc/ssl/certs/ca.crt"{{ else }}{{ .Values.app.env.Aspire__MongoDB__Driver__ConnectionString | quote }}{{ end }}
            - name: Aspire__StackExchange__Redis__ConnectionString
              value: {{ if .Values.redis.tls.enabled }}"{{ include "serviceexample.fullname" . }}-redis:6379,ssl=true,sslProtocols=Tls12,abortConnect=false"{{ else }}{{ .Values.app.env.Aspire__StackExchange__Redis__ConnectionString | quote }}{{ end }}
            - name: Aspire__NATS__Net__ConnectionString
              value: {{ if .Values.nats.tls.enabled }}"tls://{{ include "serviceexample.fullname" . }}-nats:4222"{{ else }}{{ .Values.app.env.Aspire__NATS__Net__ConnectionString | quote }}{{ end }}
            # TLS Configuration Environment Variables
            - name: MONGODB_TLS_ENABLED
              value: {{ .Values.mongodb.tls.enabled | default false | toString | quote }}
            - name: REDIS_TLS_ENABLED
              value: {{ .Values.redis.tls.enabled | default false | toString | quote }}
            - name: NATS_TLS_ENABLED
              value: {{ .Values.nats.tls.enabled | default false | toString | quote }}
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/ssl/certs
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tls-certs
          secret:
            secretName: {{ .Values.mongodb.tls.secretName | default (printf "%s-mongodb-tls" (include "serviceexample.fullname" .)) }}
