apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: monitoring
data:
  nats.conf: |
    # NATS Server Configuration
    port: 4222
    
    # HTTP monitoring port
    http: 8222
    
    # Server name
    server_name: $SERVER_NAME
    
    # Logging
    logtime: true
    
    # Authorization (disabled for simplicity)
    authorization {
      timeout: 2
    }
