apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats-exporter-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-nats-exporter
  endpoints:
  - port: metrics
    interval: 30s
