replicaCount: 1

# Main Application Image from ACR
image:
  repository: serviceexampleacr.azurecr.io/serviceexample
  tag: latest
  pullPolicy: IfNotPresent

# ... rest of values.yaml remains the same
