# values.yaml
replicaCount: 1

image:
  repository: serviceexampleacr.azurecr.io/serviceexample
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: serviceexample.local
      paths:
        - path: /
          pathType: Prefix

imagePullSecrets:
  - name: acr-secret

# Environment variables for your application
app:
  env:
    ASPNETCORE_ENVIRONMENT: "Production"
    ASPNETCORE_URLS: "http://*:9080"
    Aspire__MongoDB__Driver__ConnectionString: "mongodb://mongo:27017"
    Aspire__StackExchange__Redis__ConnectionString: "redis:6379"
    Aspire__NATS__Net__ConnectionString: "nats://nats:4222"

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
