replicaCount: 1

image:
  repository: serviceexampleacr.azurecr.io/serviceexample
  tag: latest
  pullPolicy: IfNotPresent

# Image Pull Secrets for ACR
imagePullSecrets:
  - name: acr-secret

# Service Configuration
service:
  type: ClusterIP

# App Configuration
app:
  port: 8080
  env:
    ASPNETCORE_ENVIRONMENT: "Production"
    Aspire__MongoDB__Driver__ConnectionString: "mongodb://serviceexample-mongodb:27017"
    Aspire__StackExchange__Redis__ConnectionString: "serviceexample-redis-master:6379"
    Aspire__NATS__Net__ConnectionString: "nats://serviceexample-nats:4222"

# Resource Configuration
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# Auto-scaling Configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Dependencies Configuration
mongodb:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  persistence:
    enabled: false
  imagePullSecrets:
    - name: acr-secret

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  imagePullSecrets:
    - name: acr-secret

nats:
  enabled: true
  nats:
    image: nats:latest
  cluster:
    enabled: false
