replicaCount: 1

image:
  repository: serviceexampleacr.azurecr.io/serviceexample
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9080

imagePullSecrets: acr-secret

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
