replicaCount: 1

# Main Application Image from ACR
image:
  repository: serviceexampleacr.azurecr.io/serviceexample
  tag: latest
  pullPolicy: IfNotPresent

# Service Configuration
service:
  type: ClusterIP
  port: 80

# Autoscaling Configuration
autoscaling:
  enabled: false

# Image Pull Secrets for ACR
imagePullSecrets:
  - name: acr-secret

# MongoDB with Local Path storage
mongodb:
  enabled: true
  architecture: "standalone"
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "local-path"
  auth:
    enabled: false

# Redis with Local Path storage
redis:
  enabled: true
  architecture: "standalone"
  master:
    persistence:
      enabled: true
      size: 1Gi
      storageClass: "local-path"
  replica:
    replication: false
    persistence:
      enabled: false

# NATS configuration
nats:
  enabled: true

# Add any other existing configurations you had
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true

podSecurityContext: {}
securityContext: {}

resources: {}
