apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
  labels:
    app: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
  - port: 9080
    name: http
  selector:
    app: {{ .Release.Name }}
