{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: serviceexample
  labels:
    app: serviceexample
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: serviceexample.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: serviceexample
            port:
              number: {{ .Values.service.port }}
{{- end }}
