{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "serviceexample.fullname" . }}-mongodb
  labels:
    {{- include "serviceexample.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "serviceexample.name" . }}-mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "serviceexample.name" . }}-mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}
        imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "serviceexample"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: {{ include "serviceexample.fullname" . }}-mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "serviceexample.fullname" . }}-mongodb
  labels:
    {{- include "serviceexample.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: {{ include "serviceexample.name" . }}-mongodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "serviceexample.fullname" . }}-mongodb
  labels:
    {{- include "serviceexample.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
  {{- if .Values.mongodb.persistence.storageClass }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  {{- end }}
{{- end }}
