{{- if .Values.mongodb.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  template:
    spec:
      containers:
      - name: mongodb
        volumeMounts:
        - name: datadir
          mountPath: /bitnami/mongodb
      volumes:
      - name: datadir
        emptyDir: {}
{{- end }}
