{{- if .Values.nats.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "serviceexample.fullname" . }}-nats
  labels:
    {{- include "serviceexample.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "serviceexample.name" . }}-nats
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "serviceexample.name" . }}-nats
    spec:
      hostNetwork: true
      containers:
      - name: nats
        image: {{ .Values.nats.image.repository }}:{{ .Values.nats.image.tag }}
        imagePullPolicy: {{ .Values.nats.image.pullPolicy }}
        ports:
        - containerPort: 4222
        resources:
          {{- toYaml .Values.nats.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "serviceexample.fullname" . }}-nats
  labels:
    {{- include "serviceexample.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  ports:
  - port: 4222
    targetPort: 4222
  selector:
    app.kubernetes.io/name: {{ include "serviceexample.name" . }}-nats
{{- end }}
