{{- if .Values.redis.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-redis-master
spec:
  template:
    spec:
      containers:
      - name: redis
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}
  volumeClaimTemplates: []
{{- end }}
