name: Release Helm Chart

on:
  push:
    branches: [ main ]
    paths: [ 'helm-charts/**' ]
  release:
    types: [ published ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.0'
          
      - name: Test Helm Chart
        run: |
          cd helm-charts/serviceexample
          helm dependency update
          helm lint . --strict
          helm template test . --debug

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Helm
        uses: azure/setup-helm@v3
        
      - name: Package Helm Chart
        run: |
          cd helm-charts/serviceexample
          helm dependency update
          helm package .
          mkdir -p ../../helm-repo
          cp *.tgz ../../helm-repo/
          
      - name: Create Helm Repository Index
        run: |
          helm repo index helm-repo --url https://priyankakanna.github.io/ServiceExample/helm-repo
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./helm-repo
          keep_files: true
